### ISSUE TITLE
NPM - Error: Cannot find module ...

### ISSUE THREAD

**Issue by jtheberge** [dsmorse/gridster.js#102]
When imported, a few errors appear for me. 
    
    ./~/dsmorse-gridster/dist/jquery.gridster.js
    Module not found: Error: Can't resolve './jquery.coords.js' in ...

    ./~/dsmorse-gridster/dist/jquery.gridster.js
    Module not found: Error: Can't resolve './jquery.draggable.js' in ...

    ./~/dsmorse-gridster/dist/jquery.gridster.js
    Module not found: Error: Can't resolve './jquery.collision.js' in ...

    ./~/dsmorse-gridster/dist/jquery.gridster.js
    Module not found: Error: Can't resolve './utils.js' in ...

These files do not exist in the distro, am I doing something wrong?

**Comment by jtheberge** [comment]
I had to write:
import $ from 'jquery'

Previously I was writing import Jquery from 'jquery'.

**Comment by elisiri** [comment]
I still have the jquery.draggable.js problem...

**Comment by fixmycode** [comment]
@elisiri the new release should take care of the issue as of #116 but I have no release date for the new dist, sorry it took so long.
