### ISSUE TITLE
Bug in fn.resizable (this.limit should be this.options.limit)

### ISSUE THREAD

**Issue by dswitzer** [dsmorse/gridster.js#108]
There's a bug in the last version of 0.7.0 (dated 2017-03-27).

In the `fn.resizable` method it's incorrectly referencing the `limit` option:

```
			limit: { width: this.options.max_cols !== Infinity || this.limit.width, height: this.options.max_rows !== Infinity || this.limit.height },

```

I believe this line should be:

```
			limit: { width: this.options.max_cols !== Infinity || this.options.limit.width, height: this.options.max_rows !== Infinity || this.options.limit.height },
```

**Comment by Strangemother** [comment]
I have the same issue

**Comment by fixmycode** [comment]
this change was applied on PR #91 on March of '17 but apparently nobody has rebuilt the dist folder since. I'll look into it, but the issue will be closed. Thanks for bringing this up.
