### ISSUE TITLE
Widget Position Arrangement

### ISSUE THREAD

**Issue by callranjithkani** [dsmorse/gridster.js#115]
Hi,

Any Possibility to arrange widgets in Left& UP Position Please Refer Link

https://tiberiuzuld.github.io/angular-gridster2/angular/

In Settings 
![image](https://user-images.githubusercontent.com/29392902/37912386-0d9eea96-3130-11e8-8ac4-b987332f1d3d.png) Icon choose Compant Type Left & UP , is it possible to implement

**Comment by fixmycode** [comment]
I believe the center alignment is probably part of the angular-gridster2 demo and nothing to do with gridster itself. In a fresh copy of gridster, the cells have no text alignment rules on them. See the [jquery.gridster.css](https://github.com/dsmorse/gridster.js/blob/master/dist/jquery.gridster.css) file and look it up for yourself.

you can define your own behavior for text alignment by creating a rule that overwrites the `.gridster li {}` rule.
