### ISSUE TITLE
Show image in gridster cells

### ISSUE THREAD

**Issue by iubaid** [dsmorse/gridster.js#117]
Hey,
I want to show "PLUS or ADD" icon in gridster each cell for better UI. But I am unable to add them  even I customized the default gridster.html and .css but not a required result is retrieved.

**Comment by fixmycode** [comment]
@iubaid that would be a good feature to build on top of gridster, but I think it would be out of the scope of the project itself, many people use gridster for different use cases and yours is very specific.

The first problem you need to solve is that gridster doesn't define a "grid", so there are no empty cells to start with, the structure is defined by the already existing cells. you'd need to add a temporary cell wherever you want to show a new element, and probably discard it before the serialization process starts so it's not part of your structure.
