### ISSUE TITLE
rebuild the dist and publish to NPM

### ISSUE THREAD

**Issue by fixmycode** [dsmorse/gridster.js#121]
The last build on NPM dates from a year ago and carries issues that make it impossible to work with in newer versions of Node, PR #116 solves the issue with the relative packages not showing on the dist folder and we're now ready to publish those changes.

@dsmorse I know you're super busy but you're the only one with access to the registry, could you do the honors?.

**Comment by baconbrad** [comment]
Sorry, I have since went inactive with it. I will transfer ownership of the package. Is your NPM account also dsmorse?

**Comment by baconbrad** [comment]
@dsmorse Sorry, I have since went inactive with it. I will transfer ownership of the package. Is your NPM account also dsmorse?

**Comment by baconbrad** [comment]
@dsmorse Added what I hope is your account to the maintainers. Once you have access you can feel free to remove me as I will not be able to actively maintain it.

**Comment by baconbrad** [comment]
@fixmycode @dsmorse The package has been updated. 0.7.1 has been reverted as it did not contain a rebuilt version. 0.7.2 has been rebuilt with Grunt.

**Comment by dsmorse** [comment]
thank you @baconbrad ... yes dsmorse is my user id there too, and I can confirm I see it. I will test publishing 0.8.0 tonight.  @fixmycode if you want to have rights to npm as well let me know your UID

**Comment by fixmycode** [comment]
@dsmorse it's **fixmycode** 😃

**Comment by dsmorse** [comment]
done.  I have published 0.8 and added you with write permisions
