### ISSUE TITLE
Rails gem does not include the stylesheets/javascripts

### ISSUE THREAD

**Issue by ened** [dsmorse/gridster.js#13]
For some reason the vendor/ directory is not bundled in the gem right now.

**Comment by dsmorse** [comment]
could it be that you have the the gitignore ignore the vendor folder then the gemspec asks git to list the files?

**Comment by ened** [comment]
Yes so I tried fixing that to no success. The gem name changed too, slightly. Can this be reverted?

**Comment by dsmorse** [comment]
I had to change the gem name, because there was a conflict on rubygems and I don't have permissions to overwrite the other persons stuff.

**Comment by dsmorse** [comment]
try it now.  I updated the build configs and pushed 0.6.9.1

**Comment by ened** [comment]
@dsmorse yes I believe that was the problem for the vendor directory. The other issue which prevented the gem from working is fixed in #15

**Comment by dsmorse** [comment]
#14 & #15 have been merged.  I'll push 0.6.9.2 to rubygems

**Comment by ened** [comment]
0.6.10 √ 

Thanks @dsmorse .
