### ISSUE TITLE
Bug enable_resize and disable_resize

### ISSUE THREAD

**Issue by anarsyakir** [dsmorse/gridster.js#136]
I got a bugs when using enable_resize and disable_resize method, shown in this picture

![image](https://user-images.githubusercontent.com/13670192/65019360-4257ab00-d955-11e9-8c32-1f4fe4f3a6c8.png)

```javascript
jquery.gridster.min.js:1 Uncaught TypeError: Cannot read property 'enable' of undefined
    at d.h.enable_resize (jquery.gridster.min.js:1)
    at HTMLAnchorElement.<anonymous> (skeleton:261)
    at HTMLAnchorElement.dispatch (jquery-3.3.1.js:5183)
    at HTMLAnchorElement.elemData.handle (jquery-3.3.1.js:4991)
```

my code

```javascript
var gridster = $(".gridster ul").gridster().data('gridster');
gridster.enable_resize();
```

Hope you will fix it!. Thanks

**Comment by fixmycode** [comment]
I think this is a little counter-intuitive, and according to the code documentation the method should enable the feature, but for now, you need to initialize the instance with the following:

    var gridster = $(".gridster ul").gridster({resize: {enabled: true}}).data('gridster');

After that, the instance should be resizable from the start, and you can disable the feature by using `gridster.disable_resize()` and turning it back on with `gridster.enable_resize()`

**Comment by anarsyakir** [comment]
Thanks for your reply.

That solve my issue. Thanks again.

I didn't know if calling `gridster().data()` will re-initialize the gridster option (resize enabled)

i use the first gridster init as a global variable, so don't need to recall it again.

```javascript
var gridster = $('.widgetman-widgets ul').gridster({
        max_cols: 6,
        widget_margins: [10, 10],
        widget_base_dimensions: [150, 150],
        resize : {
            enabled : true
        }
    }).data('gridster');
```

I will close this issue. Thanks in advance!
