### ISSUE TITLE
missing description for -with-extras version

### ISSUE THREAD

**Issue by pySilver** [dsmorse/gridster.js#17]
Hi!

Thanks for keeping this fork updated. I have a question – What is the difference between regular and -with-extras packages?

**Comment by dsmorse** [comment]
The with extras was some work that ducksboard did to add a 8 new functions for a TV display.  I think they were considered experimental, and never moved into the main baseline.

You can see the additional functions here: https://github.com/dsmorse/gridster.js/blob/master/src/jquery.gridster.extras.js

**Comment by pySilver** [comment]
@dsmorse thx for info. I'm also wondering about max_size_x which states:
``The maximum number of columns that a widget can span.``

I've tried to change this value and well it doesn't seem to affect anything.

**Comment by dsmorse** [comment]
You can see a working example on the demo page:
http://dsmorse.github.io/gridster.js/demos/resize-limits.html
