### ISSUE TITLE
Add Browserify support

### ISSUE THREAD

**Issue by gszabo** [dsmorse/gridster.js#18]
CommonJS support is present in the library, and the `dist/jquery.gridster.js` file contains lines like `require('./jquery.draggable.js')`. However, the `jquery.draggable.js` file is not present in the `dist` folder, since it is concatenated into the main `jquery.gridster.js` file. The result is that Browserify cannot include this library.

Two possible solutions:
1) include `src` directory as an exception in `.npmignore`, so it is fetched via `npm install`
2) fix the CommonJS support to only require `jquery` in the `dist` folder and do not use relative paths

**Comment by dsmorse** [comment]
I would prefer options 2.  Would you please submit a pull request with the changes.

**Comment by gszabo** [comment]
I would also prefer option 2 and tried to make it happen, but unfortunately did not find a way to remove those `require('...')` statements with grunt. Do you have any idea?

**Comment by fixmycode** [comment]
This was fixed on PR #116 by coping the required files into the dist folder. Not the most elegant solution but it will work until we have a new build system in place.
