### ISSUE TITLE
Responsive grid width bug - drop target draws in wrong place

### ISSUE THREAD

**Issue by rmundell** [dsmorse/gridster.js#3]
We love gridster and we love even more your enhancements to make it responsive but I think we've found a bug.

If you open the "Responsive grid width" (http://dsmorse.github.io/gridster.js/demos/responsive.html) demo in a small window and resize the browser window bigger (or maximize it). 

If you drag one of the smaller tiles from the left hand size, as you move it right the drop target highlighting gets further and further to the right, and as it's to the right-most side of the screen it's almost a full column out of position to the right.

Sorry, but I haven't dived into the code to try to figure it out but my guess would some of the math isn't quite right when it's calculating the drop position relative to the window scaling.

**Comment by dsmorse** [comment]
which browser are you you using?  I tried a few combinations and haven't been able to see the issue as you describe it.

**Comment by rmundell** [comment]
Hmmmm… this is really strange. I was able to recreate it for about an hour for both your demos and my own test version in both IE11 and Chrome, but now the problem’s gone away. Strange. If I can get a recreateable test case I’ll let you know.

**Comment by dsmorse** [comment]
Glad to hear it's fixed.

**Comment by kennethmyers** [comment]
I'm actually having the same issue in both Firefox (ESR 38.0) and Chromium (Version 43.0.2357.130 Built from source for Red Hat Enterprise Linux Server release 6.6 (Santiago) (64-bit))

**Comment by azatTemirbek** [comment]
GO TO : http://dsmorse.github.io/gridster.js/demos/responsive.html
rearrange the items in order to leave free space on the right. Then press F12 key now try to move any left item to the right edge.


![DRAGdROP](https://user-images.githubusercontent.com/12012594/60331534-8a41e400-999d-11e9-971d-c877aa8de4c8.PNG)
