### ISSUE TITLE
Bug with Sticky Position Widgets

### ISSUE THREAD

**Issue by bgandham** [dsmorse/gridster.js#30]
Attached video shows couple of simple scenarios in which widgets get overlapped.  It's easier re-producing this with bigger widgets over smaller widgets.  Once it happens the corruption keeps extending.

http://1drv.ms/1gkOwmK

**Comment by thorstenroth** [comment]
Hi, having the same issue. Would be great if somebody could resolve it.
Thanks

**Comment by cwoolf** [comment]
Likewise, hope a fix is created soon.

**Comment by shibaogang** [comment]
Ran into the same problem, it'd be great to have it fixed.
Thanks

**Comment by LbISS** [comment]
Still the same issue.

**Comment by M0nter0** [comment]
I'm working on it. I guess I could do the pull request this weekend.
