### ISSUE TITLE
Latest release do not match latest version

### ISSUE THREAD

**Issue by M0nter0** [dsmorse/gridster.js#41]
I'm working on issue #30, but when I fork the project, latest version of [distributed jquery.gridster.js](https://github.com/dsmorse/gridster.js/blob/master/dist/jquery.gridster.js) do not match [latest release](https://github.com/dsmorse/gridster.js/releases/tag/v0.6.10)

Latest version has last modification v0.6.10 - 2016-01-21
Latest release has last modification v0.6.10 - 2015-05-31

Should we update the latest release?

**Comment by dsmorse** [comment]
I'll drop a new release with all the recent changes
