### ISSUE TITLE
Moving widgets with a width greater than one wont move across one space.

### ISSUE THREAD

**Issue by WigglesTehPro** [dsmorse/gridster.js#52]
These two images below show the issue.

![gridstererrorpart1](https://cloud.githubusercontent.com/assets/11716445/15010092/2d089478-11e2-11e6-8b74-4e329637bfc7.PNG)

![image](https://cloud.githubusercontent.com/assets/11716445/15010073/1d8c78a2-11e2-11e6-8543-c375daa8ce1f.png)

**Comment by robertadsoft** [comment]
I'm experiencing the same issue. After playing with the widget a little the smaller position becomes available again.

**Comment by DaTebe** [comment]
Is there a solution to this "problem". E.G. in Kibana it works very well. But they use the ducksboard version 0.5.6

**Comment by andreityuhai** [comment]
It's duplicate of #44
