### ISSUE TITLE
Limit Grid size (Columns & Rows)

### ISSUE THREAD

**Issue by adminnz** [dsmorse/gridster.js#59]
There does not appear to be an example of limiting the grid size in terms of max number of columns & max number of rows.

How would I got about limiting the maximum size of the grid (in terms of columns/rows, or even just in terms of max height/width pixels) ?

**Comment by WigglesTehPro** [comment]
namespace: '',
				widget_selector: 'li',
				static_class: 'static',
				widget_margins: [10, 10],
				widget_base_dimensions: [400, 225],
				extra_rows: 0,
				extra_cols: 0,
				min_cols: 1,
				**max_cols: Infinity,** <<---
				min_rows: 1,
				**max_rows: 15,** <<---
				autogenerate_stylesheet: true,
				avoid_overlapped_widgets: true,
				auto_init: true,
				center_widgets: false,
				responsive_breakpoint: false,
				scroll_container: window,
				shift_larger_widgets_down: true,
				move_widgets_down_only: false,
				shift_widgets_up: true,

you can set the two parameters in bold to the max cols and rows

**Comment by webbird** [comment]
I needed a grid with static column count, so setting min and max to the same value worked perfectly for me. I combined it with Bootstrap panels. See my code below.

```
$(function(){ //DOM Ready
        gridster = $(".gridster ul").gridster({
            widget_base_dimensions: ['auto', 140],
            autogenerate_stylesheet: true,
            min_cols: 3,
            max_cols: 3,
            widget_margins: [5, 5],
            resize: {
                enabled: false
            },
            draggable: {
                handle: ".panel-heading"
            }
        }).data('gridster');
    });
```

**Comment by dsmorse** [comment]
thanks webbird
