### ISSUE TITLE
Allow widgets to not always pull up

### ISSUE THREAD

**Issue by ericop** [dsmorse/gridster.js#6]
So we have a month old version of Gridster where we gutted `fn.on_stop_overlapping_row` and just have a return statement and also removed `this.can_go_player_up` from `fn.set_player`  (commit was :https://github.com/ericop/gridster.js/commit/c331dfc8bec46728cfeb138743bc6c50eeb4bafa) .  This allowed for placing widgets anywhere, and having rows of white space so that "anti-gravity" didn't force them to slide up after they're placed. In the current version (0.6.8) this little trick doesn't work - widgets aren't even draggable actually after i tried a merge - but do you know of an official way we could "turn off" the anti-gravity with a `options.autoup: false` , etc. ? Thoughts? 

I really appreciate your take this project over. It's super fun and "has good bones". I'd love to see it kept alive and strong for a long time to come!

**Comment by ericop** [comment]
@dsmorse not sure how interested you are in adding some features for pay. We'd obviously give you more clear acceptance criteria, and you could merge these features back into the open source repo. We are just a small shop and and trying to get what we want for usability out of Gridster is spreading us a little thin. Shoot me an email if you're interested in some sort of arrangement along these lines. We love sponsoring good open-source!

Two main features we're looking at:
- Allow widgets to be placed anywhere and have them not slide upwards, but stay put
- Only have widget collision move the widget underneath after mouseup (i.e., not have cards move from collision while dragging, but only the widget your player's placeholder is over over when you're done.)

http://recordit.co/H9kFmk9tOy displays the features I'm talking about, but they are in the month old version of Gridster and we'd love to have them as toggle options and have the auto-scroll and some of the other newness working for us, from your current build.

**Comment by dsmorse** [comment]
I'm not opposed to such an arrangement and I could see those as good features.. but it would depend on your timelines, as I've got my deliveries to coordinate too.  Since it looks like you have it working in an older code base it shouldn't be that difficult to get it on the latest.

**Comment by ericop** [comment]
I am CCing George, on of the guys in charge over hear who was the
originator of this good idea. He can hopefully weigh in on the time line
and financial aspects.

wait_for_mouseup is the option I added in the old one to avoid updating
widgets every collision as seen in this commit
https://github.com/ericop/gridster.js/commit/b544741a7c6a8cfeb4b475f39f3fd99d71d737ba
. One known issue is that since the widgets aren't updating on_drag, when
the active player being dragged overlaps part of his original position when
you're done with the drag, it snaps back to its original location from
before the drag.

Eric Johnson 517-927-4301

**Comment by ericop** [comment]
Also just for pin-point clarity, the goal is just to move the last widget that you drop the player on, not to retroactively move all the widgets you hovered or dragged over in the process.

**Comment by ericop** [comment]
We would like to have the change done by June 1st.  Is that possible? 

Give me a call at my cell number below and we can discuss cost, timing, and the change.

George

 
cell 		517.304.3254
office 	248.651.5979
fax 		248.651.9583
website: www.eFlexSystems.com <http://www.eflexassembly.com/>
Linkedin:  www.linkedin.com/in/georgejewell/

**Comment by dsmorse** [comment]
Due to conflicts with my own release schedule, I won't be able to commit to that deadline:  but I took some time to look at your changes, check out the beta demo:  http://dsmorse.github.io/gridster.js/demos/sticky-postion.html

**Comment by ericop** [comment]
Also our settings are as follows if you want to test under the same conditions.

```
// Build Gridster
  _loadGridster: function() {
    var gridster, ref;
    return gridster = (ref = this.$(".task-card-list")) != null ? ref.gridster({
      max_cols: 10,
      max_rows: 10,
      autogrow_cols: true,
      autogrow_rows: true,
      widget_base_dimensions: this.get('widgetBaseDimensions'),
      resize: {
        enabled: true,
        axes: ['y'],
        handle_append_to: '.task-card',
        handle_class: 'task-resize-handle',
        stop: Em.run.bind(this, '_findAllCoordsData')
      },
      draggable: {
        stop: Em.run.bind(this, '_findAllCoordsData')
      },
      collision: {
        wait_for_mouseup: true
      }
    }) : void 0;
  },

// We toggle the base dimensions for an “overview mode"
  widgetBaseDimensions: (function() {
    if (this.get('isCollapsed')) {
      return [250, 87];
    } else {
      return [250, 230];
    }
  }).property('isCollapsed').readOnly(),


  _resizeBaseDimGridster: function() {
    return this.get('gridster').resize_widget_dimensions({
      widget_base_dimensions: this.get('widgetBaseDimensions')
    });
  },

// These are examples of what we need (col, row & sizeY for each widget) for 
//   callbacks after drag and resize  `stop`
  _findAllCoordsData: function() {
    var ref;
    if ((ref = this.$('.task-card-holder')) != null) {
      ref.each((function(_this) {
        return function(i, elem) {
          return _this._updateTaskCoordinates($(elem));
        };
      })(this));
    }
 
  },
  _updateTaskCoordinates: function(elem) {
    var column, row, sizeY, subtask;
    subtask = Ember.View.views[elem.attr('id')].get('subtask');
    column = parseInt(elem.attr('data-col'));
    row = parseInt(elem.attr('data-row'));
    sizeY = parseInt(elem.attr('data-sizey'));
    subtask({
      column: column,
      row: row,
      sizeY: sizeY
    });
    return console.log('col=' + subtask.column + ', row=' + subtask.row + ', sizeY=' + subtask.sizeY);
  }
});
```



Eric D. Johnson
eFlex Systems
cell: (517) 927-4301

On May 18, 2015 at 10:15:30 AM, George Jewell (georgejewell@eflexsystems.com) wrote:

We would like to have the change done by June 1st.  Is that possible? 

Give me a call at my cell number below and we can discuss cost, timing, and the change.

George

 
cell  517.304.3254
office  248.651.5979
fax  248.651.9583
website: www.eFlexSystems.com
Linkedin:  www.linkedin.com/in/georgejewell/



On May 16, 2015, at 7:33 PM, EOP Johnson <eric.op.johnson@gmail.com> wrote:

I am CCing George, on of the guys in charge over hear who was the originator of this good idea. He can hopefully weigh in on the time line and financial aspects.

wait_for_mouseup is the option I added in the old one to avoid updating widgets every collision as seen in this commit https://github.com/ericop/gridster.js/commit/b544741a7c6a8cfeb4b475f39f3fd99d71d737ba . One known issue is that since the widgets aren't updating on_drag, when the active player being dragged overlaps part of his original position when you're done with the drag, it snaps back to its original location from before the drag.

Eric Johnson 517-927-4301

On May 16, 2015 5:13 PM, "dsmorse" <notifications@github.com> wrote:
I'm not opposed to such an arrangement and I could see those as good features.. but it would depend on your timelines, as I've got my deliveries to coordinate too. Since it looks like you have it working in an older code base it shouldn't be that difficult to get it on the latest.

**Comment by ericop** [comment]
@dsmorse So for widget "8" on http://jsbin.com/zunuqiwefe/1/edit?html,console,output I've notived that he isn't initialized to his spot properly. I'll look at it too, but if you know where we need to modify the initialize logic I'd welcome it.

**Comment by ericop** [comment]
![image](https://cloud.githubusercontent.com/assets/5218249/7685163/fc8f5afe-fd59-11e4-8e2d-1160126393df.png)

**Comment by dsmorse** [comment]
Yeah, I did say beta (right?)  I've also noticed in this config an error with the larger component not pushing enough space if there is an opening.... The things stay where you put them works well, the things move is clearly buggy.  And it appears that the init logicstill has some 'push to the top' logic in register_widget which is why 8 is sliding to row 3 vs row 4 where we told him to go.

**Comment by ericop** [comment]
Totally understandable. I'm with you on "a step at a time", just wanted to show you in case you didn't try it out and your speedy weekend beta work.

**Comment by dsmorse** [comment]
a better beta is available.. but I'm not sure I'll have more time to firm it up.  http://dsmorse.github.io/gridster.js/demos/sticky-postion.html

**Comment by ericop** [comment]
Cool man, that is better.

**Comment by kennethmyers** [comment]
@dsmorse 

That's working great for me.

And thanks for keeping this project alive!
