### ISSUE TITLE
Impossible to swap with neighboring tile

### ISSUE THREAD

**Issue by DyckGerman** [dsmorse/gridster.js#63]
Steps to reproduce:
1. Open http://dsmorse.github.io/gridster.js/ page.
2. Drag tile with "drag me" text right to overlap right side sibling. Don't release it.
Result:
![image](https://cloud.githubusercontent.com/assets/7316354/17885634/bf126cfe-6926-11e6-963e-2a366167d303.png)
Right side sibling does not swap
Expected behavior;
Sibling tiles swap on overlapping start.

**Comment by oyeaussie** [comment]
This issue still exists in 0.7.0.

Can you please confirm that this is resolved?
