### ISSUE TITLE
Update or remove gridster.net link

### ISSUE THREAD

**Issue by vwchu** [dsmorse/gridster.js#69]
The referred website for the documentation: gridster.net seem to be incorrect and pointed me to phishing website. You probably should remove references of it from the README and Github description.

**Comment by dsmorse** [comment]
looks like the owner of the original domain let the reg slide.  Not surprising since he stopped accepting pull requests a while ago.

This version's site is hosted on github:  http://dsmorse.github.io/gridster.js/
