### ISSUE TITLE
Widgets that overlap get dropped

### ISSUE THREAD

**Issue by zeroedin-bill** [dsmorse/gridster.js#9]
If avoid_overlapped_widgets is true (default), widgets that overlap result in some widgets being dropped from the DOM. A better behavior would be for the losing widgets to get added to the bottom.

Example options:

```js
var gridsterOpts = $.extend({}, {
    widget_margins: [widgetMargins, widgetMargins],
    min_cols: 3,
    max_cols: max_cols, // Needs to go depending on the dashboard defs
    max_rows: 40,
    widget_base_dimensions: ['auto', 30],
    shift_larger_widgets_down: true,
    autogenerate_stylesheet: true,
    serialize_params: this.widgetSerializer,
    avoid_overlapped_widgets: true,
    shift_widgets_up: true,
    resize: {
        enabled: options.canEdit,
        start: $.proxy(this.widgetResizeStarted, this),
        stop: $.proxy(this.widgetResizeStopped, this)
    }
}, options);
this.$el.gridster(gridsterOpts);
```

**Comment by dsmorse** [comment]
Agree... and I just ran into this issue myself this week.  Are you working a fix or just reporting it?

**Comment by zeroedin-bill** [comment]
@dsmorse Just reporting it - sadly don't have time to fix it this week.

**Comment by dsmorse** [comment]
Line 2082 of register_widget has this if clause:
			if (!$el.hasClass('.disp_ad')) {
				$el.remove();
				return false;
			}
Dustin added the check in commit: 3ebf5fa95e6028d59bff16d557576e47534db607	(12.10.12)		
However, There is no documentation as to what that class means, I'm removing the if clause
